### ISSUE TITLE
Debugging SwaggerUI

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#126]
Some issues spotted following #123:

- [x] The routes at the API docs miss the trailing "/", so when you "Try it out" requests go to grlc.io/api/user/repoop instead of repo/op and thus fail
- [x] Some CSS seem missing -- the footer links to "Oh yeah" and previous and next spec version links do not have styles
- [x] Also when "trying out" calls, the form fails to validate some parameters even if they're correct (e.g. literal strings)
- [ ] There's a resource that fails to load, requesting blob:http://grlc.io/ which is not found (the previous might be related to this)
- [x] New branch for testing
- [x] Testing instance

**Comment by c-martinez** [comment]
Fixes: 
 - Path names now start with `/`
 - `literal` strings are changed to type `string` in order for validation to work
 - Pushing changes to branch `dev` @albertmeronyo -- can you setup a test instance base on `dev` branch?

Indeed -- no CSS for footer links (because it is not part of the SwaggerUI block -- we can add some custom CSS.

Not sure which resource is failing to load -- could you give more details @albertmeronyo ?

**Comment by c-martinez** [comment]
Added CSS to `oh yeah?`, `prev` and `next` buttons.

**Comment by c-martinez** [comment]
Merged #127 -- ready for deploying on test instance.

**Comment by albertmeronyo** [comment]
Awesome, thanks for all these @c-martinez !
I've set up a dev instance at http://dev.grlc.io/ :
- Pushes to the :dev branch trigger image builds at docker hub
- Every night at 1am the latest dev image at docker hub is pulled in the server and the image is restarted

If you need me to force this last one please let me know!

**Comment by c-martinez** [comment]
Thanks for setting it up @albertmeronyo !

But actually, I'm not sure if it is building the image properly -- description box on `http://dev.grlc.io/api/albertmeronyo/lodapi/` looks like a black box, but this was solved in #130, and should look like this:

![image](https://user-images.githubusercontent.com/7782231/42565026-99f13bfe-8502-11e8-8ee4-dda155a6d1f4.png)

Could you maybe have a look?

**Comment by albertmeronyo** [comment]
Funny - I just forced a pull + restart and the issue persists. But if I build the image locally everything looks fine.
Maybe an issue with the automatic builds at docker hub?

**Comment by c-martinez** [comment]
I think it is fixed -- did you clear your browser cache after restart? Not sure what the issue might be.

**Comment by c-martinez** [comment]
Can't find which is the resource not loading anymore, I think this is fixed. Closing issue.
